### ISSUE TITLE
Simple app w/ containers: AttributeError: 'tuple' object has no attribute '_labeled_widget_ref'

### ISSUE THREAD

**Issue by connorferster** [pyapp-kit/magicgui#512]
**Describe the bug**
I am trying to create a small gui app as a demonstration. The app is intended to take five inputs and display a table after adjusting the inputs. The error I get is as follows:

```
(aisc_db) PS C:\Users\conno\Documents\GitHub\Lesson_11\AISC Example\aisc_db> python -m gui_app
Traceback (most recent call last):
  File "C:\Users\conno\miniconda3\envs\aisc_db\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\conno\miniconda3\envs\aisc_db\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\conno\Documents\GitHub\Lesson_11\AISC Example\aisc_db\gui_app.py", line 28, in <module>
    input_container = Container(widgets=input_list)
  File "C:\Users\conno\miniconda3\envs\aisc_db\lib\site-packages\magicgui\widgets\_concrete.py", line 178, in __init__
    super(cls, self).__init__(**kwargs)
  File "C:\Users\conno\miniconda3\envs\aisc_db\lib\site-packages\magicgui\widgets\_bases\container_widget.py", line 81, in __init__
    self.extend(widgets)
  File "C:\Users\conno\miniconda3\envs\aisc_db\lib\_collections_abc.py", line 1094, in extend
    self.append(v)
  File "C:\Users\conno\miniconda3\envs\aisc_db\lib\_collections_abc.py", line 1073, in append
    self.insert(len(self), value)
  File "C:\Users\conno\miniconda3\envs\aisc_db\lib\site-packages\magicgui\widgets\_bases\container_widget.py", line 181, in insert
    _widget = _LabeledWidget(widget)
  File "C:\Users\conno\miniconda3\envs\aisc_db\lib\site-packages\magicgui\widgets\_concrete.py", line 1003, in __init__
    widget._labeled_widget_ref = ref(self)
AttributeError: 'tuple' object has no attribute '_labeled_widget_ref'
```

**To Reproduce**
1. Create "gui_app.py" with the following contents:

```python
# from aisc_db import get_section
from typing import Optional
import rich
import pandas as pd
from magicgui.widgets import Container, Label, RadioButtons, LiteralEvalLineEdit, Table, PushButton, MainWindow, SpinBox

def get_section():
    """
    Function to create some dummy data
    """
    df = pd.DataFrame(
        data = [[1, 2, 3], [4, 5, 6]],
        columns=["Col 1", "Col 2", "Col 3"]
    )
    return df

units_select = RadioButtons(choices=["US", "SI"], label="Units: "),
max_depth_text = LiteralEvalLineEdit(value="None", label="Max Depth: "),
min_depth_text = LiteralEvalLineEdit(value="None", label="Min Depth: "),
min_zx_text = LiteralEvalLineEdit(value="None", label="Min Zx: "),
min_ix_text = LiteralEvalLineEdit(value="", label="Min Ix: "),
max_records_spin = SpinBox(value=5, label="Max records to show: ")
calculate_button = PushButton(value=False, label="Get sections!")

input_list = [
    units_select,
    max_depth_text,
    min_depth_text,
    min_zx_text,
    min_ix_text,
    max_records_spin,
    calculate_button,
]

results_widget = Table()

input_container = Container(widgets=input_list)
app_container = Container(widgets=[input_container, results_widget], layout='horizontal')

# set up callbacks
@calculate_button.changed.connect
def find_sections(pressed: bool):
    if pressed:
        df = get_section(
            units=units_select.value,
            max_depth=max_depth_text.value,
            min_depth=min_depth_text.value,
            min_zx=min_zx_text.value,
            min_ix=min_iz_text.value,
            max_records=max_records_spin.value
        )
        results_widget.value = df
        
app_container.show(run=True)
```
2. Create conda environment with below versions of magicgui with the command `pip install magicgui[pyqt5]` (installed locally on 2022-11-22)
3. Activate conda environment
4. Run `python -m gui_app.py`

**Expected behavior**
Expected `app_container` to be displayed in window.

**Screenshots**
Not applicable, error message from terminal included above.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python: 3.9
 - backend: Installed with qtpy 2.3.0 (Do not know how to get Qt version on Windows)
 - magicgui version 0.6.1

**Comment by connorferster** [comment]
Aiyaaahh... My bad, I made a goof.

Error was here:
```python
units_select = RadioButtons(choices=["US", "SI"], label="Units: "),  # Why I put commas here?!
max_depth_text = LiteralEvalLineEdit(value="None", label="Max Depth: "),
min_depth_text = LiteralEvalLineEdit(value="None", label="Min Depth: "),
min_zx_text = LiteralEvalLineEdit(value="None", label="Min Zx: "),
min_ix_text = LiteralEvalLineEdit(value="", label="Min Ix: "),
```
I left commas existing at the end of these lines...which of course made them tuples. 

All good. Problem solved.
