### ISSUE TITLE
PyQt6 and widget protocol

### ISSUE THREAD

**Issue by wahabk** [pyapp-kit/magicgui#558]
**Describe the bug**
First of all thank you for developing magicgui

I am getting a widget protocol error in napari when using magicgui to add a spin-inbox

_NOTE_ This is because I am using PyQt6, which is required on Mac with apple silicon

Is support for qt6 planned for magicgui? there has been a lot of discussion on napari about it but not sure what the future looks like for magicgui

```
Traceback (most recent call last):
  File "/Users/wkawafi/code/dawn/srcPytorch/viewer/live-wire2.py", line 62, in <module>
    main(path)
  File "/Users/wkawafi/code/dawn/srcPytorch/viewer/live-wire2.py", line 47, in main
    def update_sigma(sigma: float = default_sigma):
  File "/Users/wkawafi/.virtualenvs/test39/lib/python3.9/site-packages/magicgui/type_map/_magicgui.py", line 525, in inner_func
    return cast(FunctionGui, magic_class(func, **kwargs))
  File "/Users/wkawafi/.virtualenvs/test39/lib/python3.9/site-packages/magicgui/widgets/_function_gui.py", line 191, in __init__
    widgets=list(sig.widgets(app).values()),
  File "/Users/wkawafi/.virtualenvs/test39/lib/python3.9/site-packages/magicgui/signature.py", line 229, in widgets
    {n: p.to_widget(app) for n, p in self.parameters.items()}
  File "/Users/wkawafi/.virtualenvs/test39/lib/python3.9/site-packages/magicgui/signature.py", line 229, in <dictcomp>
    {n: p.to_widget(app) for n, p in self.parameters.items()}
  File "/Users/wkawafi/.virtualenvs/test39/lib/python3.9/site-packages/magicgui/signature.py", line 133, in to_widget
    widget = create_widget(
  File "/Users/wkawafi/.virtualenvs/test39/lib/python3.9/site-packages/magicgui/widgets/bases/_create_widget.py", line 119, in create_widget
    wdg_class, opts = get_widget_class(
  File "/Users/wkawafi/.virtualenvs/test39/lib/python3.9/site-packages/magicgui/type_map/_type_map.py", line 324, in get_widget_class
    assert_protocol(widget_class, WidgetProtocol)
  File "/Users/wkawafi/.virtualenvs/test39/lib/python3.9/site-packages/magicgui/widgets/protocols.py", line 32, in assert_protocol
    _raise_protocol_error(widget_class, protocol)
  File "/Users/wkawafi/.virtualenvs/test39/lib/python3.9/site-packages/magicgui/widgets/protocols.py", line 47, in _raise_protocol_error
    raise TypeError(message)
TypeError: <class 'PyQt6.QtWidgets.QDoubleSpinBox'> does not implement 'WidgetProtocol'.
Missing methods: {'_mgui_set_min_height', '_mgui_get_enabled', '_mgui_get_native_widget', '_mgui_get_visible', '_mgui_close_widget', '_mgui_set_tooltip', '_mgui_set_height', '_mgui_set_max_height', '_mgui_get_width', '_mgui_get_root_native_widget', '_mgui_get_tooltip', '_mgui_bind_parent_change_callback', '_mgui_set_max_width', '_mgui_get_max_width', '_mgui_get_min_height', '_mgui_set_min_width', '_mgui_set_enabled', '_mgui_get_height', '_mgui_set_visible', '_mgui_get_max_height', '_mgui_render', '_mgui_get_min_width', '_mgui_set_width', '_mgui_set_parent', '_mgui_get_parent'}
```

**To Reproduce**
I made a MWE 

```python
import cv2
import magicgui
import napari

def mwe(path):
    image = cv2.imread(path)
    viewer = napari.view_image(image, rgb=True)

    @magicgui(auto_call=True,
                sigma={'widget_type': QDoubleSpinBox, 'maximum': 255, 'minimum': 0.01, 'singleStep': 5.0})
    def update_sigma(sigma: float = 5.0):
        sigma = sigma

    sigma_box = update_sigma.Gui()
    viewer.window.add_dock_widget(sigma_box, area='left')
    viewer.layers.events.changed.connect(lambda x: sigma_box.refresh_choices())

    napari.run()
```

**Expected behavior**

I expect magicgui to add a float spinbox in the left corner of my napari window

**Screenshots**

**Environment (please complete the following information):**
 - OS: **Mac OSX with M2, on ARM**
 - backend: Qt 6.4.3
 - magicgui version 0.7.2

**Comment by tlambert03** [comment]
yes magicgui has supported PyQt6 for a long time.  but you're using `widget_type` parameter wrong.  You don't directly pass a Qt or other backend widget , you pass a widget from [`magicgui.widgets`](https://pyapp-kit.github.io/magicgui/api/widgets/), or the string name of one of them... and the other kwargs must be valid kwargs for your specific widget.  

so, in this case, you would do:
```python
@magicgui(
    auto_call=True,
    sigma={"widget_type": "FloatSpinBox", "max": 255, "min": 0.01, "step": 5.0},
)
def update_sigma(sigma: float = 5.0):
    sigma = sigma
```

Also, `FloatSpinBox` is already the [default widget type for a float value](https://pyapp-kit.github.io/magicgui/type_map/), so you don't need to specify it at all.  Just do:

```python
from magicgui import magicgui

@magicgui(auto_call=True, sigma={"max": 255, "min": 0.01, "step": 5.0})
def update_sigma(sigma: float = 5.0):
    sigma = sigma
```

**Comment by wahabk** [comment]
@tlambert03 Thank you so much for your quick reply!!
